### ISSUE TITLE
rabbitClient.queueDeclare bug??

### ISSUE THREAD

**Issue by laudylcp** [vert-x3/vertx-rabbitmq-client#49] opened 2018-01-11 08:09 UTC
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:123) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:843) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:60) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$queueDeclare$15(RabbitMQClientImpl.java:288) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$forChannel$22(RabbitMQClientImpl.java:386) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:278) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80) ~[obdpps-0.0.1-fat.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:360) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:225) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117) ~[obdpps-0.0.1-fat.jar:?]
	... 9 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_144]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_144]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_144]
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[?:1.8.0_144]
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:94) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:138) ~[obdpps-0.0.1-fat.jar:?]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:541) ~[obdpps-0.0.1-fat.jar:?]
	... 1 more

The following method throw exception above, but sometimes execute successfully:

public static Future<RabbitMQClient> rabbitMQClient(Vertx vertx, String queueName){
        Future<RabbitMQClient> result = Future.future();

        if(ObjectUtils.equals(rabbitClient, null)) {

            final JsonObject config = vertx.getOrCreateContext().config().getJsonObject("rabbitmq");
            logger.trace("rabbitmq config: " + config.encodePrettily());

            RabbitMQOptions options = new RabbitMQOptions();
            options.setUser(config.getString("user", "guest"));
            options.setPassword(config.getString("password", "guest"));
            options.setHost(config.getString("host", "localhost"));
            options.setPort(config.getInteger("port", 5672));

            rabbitClient = RabbitMQClient.create(vertx, options);

            Future<Void> startFut = Future.future();
            rabbitClient.start(startRes -> {
                if (startRes.succeeded()) {
                    logger.trace("rabbitmq client started successfully. isOpenChannel: " + rabbitClient.isOpenChannel()
                            + ", isConnected: " + rabbitClient.isConnected());
                    startFut.complete();
                } else {
                    logger.error("Failed starting rabbitmq client.", startRes.cause());
                    startFut.fail(startRes.cause());
                }
            });
            startFut.compose(start -> {
                Future<Void> declareFut = Future.future();
                rabbitClient.queueDeclare(queueName, false, false, false, null, queueDeclareRes -> {
                    if (queueDeclareRes.succeeded()) {
                        logger.info("queueName: " + queueName + " declare successfully.");
                        declareFut.complete();

                    } else {
                        logger.error("Failed declare queueName: " + queueName, queueDeclareRes.cause());
                        declareFut.fail(queueDeclareRes.cause());

                    }
                });
                return declareFut;
            }).compose(declare -> {
                rabbitClient.basicQos(1, basicQosRes -> {
                    if (basicQosRes.succeeded()) {
                        logger.trace("set basic Qos=1 successfully.");
                        result.complete(rabbitClient);
                    } else {
                        logger.error("Failed set basic Qos=1.", basicQosRes.cause());
                        result.fail(basicQosRes.cause());
                    }
                });
            }, result);
        }
        else {
            result.complete(rabbitClient);
        }

        return result;
    }

**Comment by Sammers21** [comment] 2018-01-11 22:14
Can you please provide a reproducer?

**Comment by laudylcp** [comment] 2018-01-12 01:53
@Sammers21 After restarted server, The problem is not reproduce. Is it rabbitmq? Is it com.rabbitmq:amqp-client:3.6.5 ????

Throw exception occured in the following code:
rabbitClient.queueDeclare(queueName, false, false, false, null, queueDeclareRes -> {
                if (queueDeclareRes.succeeded()) {
                    logger.info("queueName: " + queueName + " declare successfully.");
                    declareFut.complete();
                } else {
                    logger.error("Failed declare queueName: " + queueName, queueDeclareRes.cause());
                    declareFut.fail(queueDeclareRes.cause());
                }
            });

**Comment by Sammers21** [comment] 2018-01-14 19:45
@laudylcp , sorry? what do you mean?

**Comment by laudylcp** [comment] 2018-01-15 01:33
@Sammers21 Sometimes there is no problem, no error, sometimes the queue statement is unsuccessful, and the above exception occurs.

**Comment by Sammers21** [comment] 2018-01-29 18:27
@laudylcp, looking at the error, I would say that there is something happened to your rabbitmq broker, not with a client. For example, i think such exception may occur when you are restarting a broker.

**Comment by Sammers21** [comment] 2018-01-29 18:28
So I think it is not a bug. 

@vietj can we close the issue?

**Closed** 2018-01-29 18:41 UTC
