### ISSUE TITLE
The correct channel must be used when doing manual acks and using multiple verticles..

### ISSUE THREAD

**Issue by javadevmtl** [vert-x3/vertx-rabbitmq-client#34] opened 2017-03-13 19:24 UTC
This is more a doc issue...

When deploying multiple verticles and using the code as below exceptions get thrown...

    String address = "my.address"; 
    //+ addressCount.incrementAndGet();
				
    vertx.eventBus().consumer(address, msg -> {
        JsonObject json = (JsonObject) msg.body();
	client.basicAck(json.getLong("deliveryTag"), false, asyncResult -> {
	    if(!asyncResult.succeeded()) {
                //asyncResult.cause().printStackTrace();
            } else {
            }
        });
    });

    // Setup the link between rabbitmq consumer and event bus address
    client.basicConsume("events", address, false, consumeResult -> {
        if (consumeResult.succeeded()) {
	    System.out.println("RabbitMQ consumer created !");
        } else {
            consumeResult.cause().printStackTrace();
        }
    });

To get around this, we have to make sure that each consumer/channel pair publish to their own eventbus addtress such as: my.address.1, my.address.2 and so on...

The exception: 

    com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 56, class-id=60, method-id=80)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:194)
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:308)
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:302)
        at com.rabbitmq.client.impl.ChannelN.basicAck(ChannelN.java:1042)
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:71)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:369)
        at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$0(RabbitMQClientImpl.java:145)
        at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$22(RabbitMQClientImpl.java:413)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:263)
        at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Sammers21** [comment] 2018-02-06 17:44
Hi, it seems that I figured the cause of the problem. Such exception occurs when we are receiving the same message from event bus at the same time on the first and on the second verticle.

Here is a quick reproducer:
```java
public class Main {
  public static void main(String[] args) throws IOException, TimeoutException {
    int count = 1000;

    List<String> sendingOrder = IntStream.range(1, count).boxed().map(Object::toString).collect(Collectors.toList());

    ConnectionFactory factory = new ConnectionFactory();
    factory.setHost("localhost");
    Channel channel = factory.newConnection().createChannel();

    channel.queueDeclare("events", false, false, false, null);
    AMQP.BasicProperties properties = new AMQP.BasicProperties.Builder().contentType("text/plain").contentEncoding("UTF-8").build();
    // send  messages
    for (String msg : sendingOrder)
      channel.basicPublish("", "events", properties, msg.getBytes("UTF-8"));
    
    Vertx vertx = Vertx.vertx();
    vertx.deployVerticle(new Verticle());
    vertx.deployVerticle(new Verticle());

  }
}

class Verticle extends AbstractVerticle {
  @Override
  public void start() throws Exception {
    String address = "my.address";
    RabbitMQClient client = RabbitMQClient.create(vertx, new RabbitMQOptions().setHost("localhost"));
    client.start(h -> {
      if (h.succeeded()) {
        System.out.println("started");
        // Setup the link between rabbitmq consumer and event bus address
        client.basicConsume("events", address, false, consumeResult -> {
          if (consumeResult.succeeded()) {
            System.out.println("RabbitMQ consumer created !");
          } else {
            System.out.println("not succeed");
            consumeResult.cause().printStackTrace();
            System.out.println(consumeResult);
          }
        });

      } else {
        System.out.println("not started");
      }
    });

    vertx.eventBus().consumer(address, msg -> {
      JsonObject json = (JsonObject) msg.body();
      System.out.println("acking " + json.getLong("deliveryTag"));
      client.basicAck(json.getLong("deliveryTag"), false, asyncResult -> {
        if (!asyncResult.succeeded()) {
          asyncResult.cause().printStackTrace();
        } else {
          System.out.println("succeed " + ((JsonObject) msg.body()).getString("body"));
        }
      });
    });
    super.start();
  }
}
```

And here is a log the application produce if you would run it: https://pastebin.com/raw/TsNi0Dxm

And if you would look at the first lines you would see such lines:
```
acking 1
acking 1
```

So, deployed verticles is trying to acknowledge the same tag.

**Comment by vietj** [comment] 2018-02-06 17:47
it's because the messages are sent with publish ?

**Comment by Sammers21** [comment] 2018-02-06 18:00
I m not sure that the problem is in the way we do publishing to rabbitmq, but in the way, we do consumption of unacknowledged messages.

The thing is that we are consuming an unacknowledged message twice and as a result sending it to an event bus twice at [RabbitMQClientImpl.java#L138](https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L138).

**Comment by Sammers21** [comment] 2018-02-06 18:16
So, I don't think the issue is an actual bug because the message can be consumed as many times as wanted until it is acknowledged. 

I think the behavior is even expected. You should be able to catch such exception and keep in mind that such exception may occur when you are trying to acknowledge already acknowledged message.

There are two ways to avoid it:

1.  use autoAck = true, when creating a consumer (recommended)
2. don't use several verticles for consumption

**Comment by Sammers21** [comment] 2018-02-06 18:18
@vietj, do you think we should cover such behavior in the documentation?

**Comment by Sammers21** [comment] 2018-02-12 13:31
@vietj , ping. Should we mention in documentation that a exception may occur when using _basicAck_ in case when message already acknowledged?

**Comment by Sammers21** [comment] 2018-02-12 13:33
and the method should be used with caution

**Comment by vietj** [comment] 2018-02-12 13:36
@Sammers21 was busy with 3.5.1 release

**Comment by vietj** [comment] 2018-02-12 13:37
can you give a description of the issue ?

**Comment by Sammers21** [comment] 2018-02-12 13:51
@vietj , sure, i can.

When setting up a consumer with **_autoAck = false_**(a param of _RabbitMQClient#basicConsume_ method) and doing manual acknowledgement then **com.rabbitmq.client.AlreadyClosedException** may occur in case when message already acknowledged by another consumer like in [the](https://github.com/vert-x3/vertx-rabbitmq-client/issues/34#issuecomment-363505051) example.

**Comment by javadevmtl** [comment] 2018-02-12 15:35
Basically when you have multiple instances deployed for the consumer, the manual ACK needs to come on the same event bus address so it can go to the correct RabbitMQ channel.

**Comment by vietj** [comment] 2018-02-14 07:59
overall I'm wondering why this use the event bus out of the box

**Comment by vietj** [comment] 2018-02-14 08:00
for instance the return tag is ignored and does not allow to cancel the basic subscription

**Comment by vietj** [comment] 2018-02-14 08:00
ideally it should use a cancellable `ReadStream` instead

**Comment by vietj** [comment] 2018-02-14 08:01
also the error handler in basic consume is just a duplicate of the resultHandler

**Comment by vietj** [comment] 2018-02-14 08:03
so I'm in favor of documenting this and coming up with a new revised API for consuming property rabbitmq queues. WDYT ?

**Comment by Sammers21** [comment] 2018-02-14 08:55
@vietj, sure, current API is not allow to cancel subscribtion and it is bad. I'm also thinking that consuming messages via event bus is not good idea. 

I'm not familiar with _ReadStream_ and implementing own ones. Can you point me out? 

And if we would use _ReadStreams_, should we remove current API or we should provide _ReadStreams_ as alternative way?

**Comment by vietj** [comment] 2018-02-14 08:56
@Sammers21 we plan in vert.x 3.6 to make easier to implement ReadStream, in the meantime you can roll out your own basic implementation. Just have a look at MessageConsumer implementation or AsyncFile to get the idea.

**Comment by vietj** [comment] 2018-02-14 16:31
I've created this issue @Sammers21 for discussing it https://github.com/vert-x3/vertx-rabbitmq-client/issues/53

**Comment by Sammers21** [comment] 2018-02-14 19:58
@vietj , great

**Comment by Sammers21** [comment] 2018-04-08 18:56
@vietj , i think this issue should be closed

**Comment by vietj** [comment] 2018-04-09 08:25
it's closed as won't fix as now we provide a queue/stream API instead to use and we won't fix the deprecated API.

**Closed by vietj** 2018-04-09 08:25 UTC
Labels: wontfix
